version: '3.8'
services:
  pc1:
    build:
      context: .
    privileged: true
    hostname: pc1
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
    command: bash -c "
      ip addr flush dev eth0
      && ip addr add 10.2.10.1/24 dev eth0
      && ip addr add fc00:1:1:1::1/64 dev eth0
      && tail -f /dev/null"
  pc2:
    build:
      context: .
    privileged: true
    hostname: pc2
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
    command: bash -c "
      ip addr flush dev eth0
      && ip addr add 10.2.10.2/24 dev eth0
      && ip addr add fc00:1:1:1::2/64 dev eth0
      && tail -f /dev/null"
