CC=gcc

all: daytimeudpcliv6 daytimeudpcliv6_sig daytimeudpcliv6_t daytimeudpsrvv6

daytimeudpcliv6: daytimeudpcliv6.c
	gcc -o daytimeudpcliv6 daytimeudpcliv6.c

daytimeudpcliv6_sig: daytimeudpcliv6_sig.c
	gcc -o daytimeudpcliv6_sig daytimeudpcliv6_sig.c

daytimeudpcliv6_t: daytimeudpcliv6_t.c
	gcc -o daytimeudpcliv6_t daytimeudpcliv6_t.c

daytimeudpsrvv6: daytimeudpsrvv6.c
	gcc -o daytimeudpsrvv6 daytimeudpsrvv6.c

clean:
	rm daytimeudpcliv6 daytimeudpcliv6_sig daytimeudpcliv6_t daytimeudpsrvv6